// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qibuwyrzeqazafknkiqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYnV3eXJ6ZXFhemFma25raXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NDcxMDMsImV4cCI6MjEwMzQyMzEwM30.ZZXrIqyXNxhwg5CSgDR4PjS_PJ4KDvaRMlKB7z2nmUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});